//
//  SecondPresenter.swift
//  EstructuraVIPER
//
//  Created GuimelGMC on 15/01/18.
//  Copyright © 2018 GuimelGMC. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SecondPresenter: SecondPresenterProtocol {

    weak private var view: SecondViewProtocol?
    var interactor: SecondInteractor?
    private let router: SecondWireframeProtocol

    init(interface: SecondViewProtocol, interactor: SecondInteractor?, router: SecondWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
