//
//  SecondProtocols.swift
//  EstructuraVIPER
//
//  Created GuimelGMC on 15/01/18.
//  Copyright © 2018 GuimelGMC. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SecondWireframeProtocol: class {

}
//MARK: Presenter -
protocol SecondPresenterProtocol: class {

}

//MARK: View -
protocol SecondViewProtocol: class {

  var presenter: SecondPresenterProtocol?  { get set }
}
