//
//  SecondViewController.swift
//  EstructuraVIPER
//
//  Created GuimelGMC on 15/01/18.
//  Copyright © 2018 GuimelGMC. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SecondView: BaseController {

	var presenter: SecondPresenterProtocol?
    var isHiddenCloseButton : Bool = true

	override func viewDidLoad() {
        super.viewDidLoad()
        
        if !isHiddenCloseButton {
            addCloseButton()
        }
    }

}

extension SecondView : SecondViewProtocol {
    
}
