//
//  SecondRouter.swift
//  EstructuraVIPER
//
//  Created GuimelGMC on 15/01/18.
//  Copyright © 2018 GuimelGMC. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SecondRouter: SecondWireframeProtocol {
    
    weak var viewController: SecondView?
    
    static func createModule(isHiddenCloseBtn : Bool = true) -> SecondView {
        // Change to get view from storyboard if not using progammatic UI
        let view = UIStoryboard(name: "SecondView", bundle: nil).instantiateViewController(withIdentifier: "SecondView") as! SecondView
        let interactor = SecondInteractor()
        let router = SecondRouter()
        let presenter = SecondPresenter(interface: view, interactor: interactor, router: router)
        
        view.isHiddenCloseButton = isHiddenCloseBtn
        view.presenter = presenter
        router.viewController = view
        
        return view
    }
}
