//
//  FirstViewViewController.swift
//  EstructuraVIPER
//
//  Created GuimelGMC on 15/01/18.
//  Copyright © 2018 GuimelGMC. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FirstView: BaseController {
    
    

	var presenter: FirstPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    
    @IBAction func openSecondView(_ sender: Any) {
        presenter?.prepareSecondViewNavigation()
    }
    @IBAction func openSecondViewNoNav(_ sender: Any) {
        presenter?.prepareSecondViewNoNavigation()
    }
    
}

extension FirstView : FirstProtocol {
    
}
