//
//  FirstViewRouter.swift
//  EstructuraVIPER
//
//  Created GuimelGMC on 15/01/18.
//  Copyright © 2018 GuimelGMC. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FirstRouter: FirstWireframeProtocol {
    
    weak var viewController: FirstView?
    
    static func createModule() -> FirstView {
        
        let view = UIStoryboard(name: "FirstView", bundle: nil).instantiateViewController(withIdentifier: "FirstView") as! FirstView
        let router = FirstRouter()
        let presenter = FirstPresenter(interface: view, router: router)
        
        view.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func openSecondViewNavigation() {
        let secondView = SecondRouter.createModule()
        viewController?.navigationController?.pushViewController(secondView, animated: true)
    }
    func openSecondViewNoNavigation(){
        let secondView = SecondRouter.createModule(isHiddenCloseBtn: false)
        let nav = UINavigationController(rootViewController: secondView)
        viewController?.present(nav, animated: true, completion: nil)
    }
}
