//
//  FirstViewProtocols.swift
//  EstructuraVIPER
//
//  Created GuimelGMC on 15/01/18.
//  Copyright © 2018 GuimelGMC. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FirstWireframeProtocol: class {
    func openSecondViewNavigation()
    func openSecondViewNoNavigation()
}
//MARK: Presenter -
protocol FirstPresenterProtocol: class {
    func prepareSecondViewNavigation()
    func prepareSecondViewNoNavigation()
}

//MARK: View -
protocol FirstProtocol: class {

  var presenter: FirstPresenterProtocol?  { get set }
}
