//
//  FirstViewPresenter.swift
//  EstructuraVIPER
//
//  Created GuimelGMC on 15/01/18.
//  Copyright © 2018 GuimelGMC. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FirstPresenter: FirstPresenterProtocol {

    weak private var view: FirstProtocol?
    private let router: FirstWireframeProtocol

    init(interface: FirstProtocol, router: FirstWireframeProtocol) {
        self.view = interface
        self.router = router
    }
    
    func prepareSecondViewNavigation() {
        router.openSecondViewNavigation()
    }
    
    func prepareSecondViewNoNavigation() {
        router.openSecondViewNoNavigation()
    }
}
